public class Practice1 {
Public String Name;
Public String Surname;
Public integer age;
Public String n, a;
Public Static String School_Name;
  String ABC = 'ABC';
    
    Public void display(){
        System.debug('Employee Name: '+Name);
			private_style();
    }

    Public static void method2(){
        System.debug('Im Static method, no need to use object here');
    }

    Private void private_style(){
        System.debug('Age is: '+ABC);
    }
    public void Practice1(String Name, String Surname){
        n= Name;
        a= Surname;
    }
}